package javaapplication;

import java.awt.Component;
import java.awt.event.ActionListener;

import javax.swing.JScrollBar;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Khan
 */
public class ClerkMain extends javax.swing.JFrame {

    protected javax.swing.JButton view_booking;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	protected javax.swing.JLabel registered_edit;
	private javax.swing.JLabel LabelForRegistered;
	/**
     * Creates new form ClerkMain
     */
    public ClerkMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        OptionPanel = new javax.swing.JPanel();
        addCustomer = new javax.swing.JButton();
        editCustomer = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        StartingPanel = new javax.swing.JPanel();
        startPanelLabel = new javax.swing.JLabel();
        BookingPanel = new javax.swing.JPanel();
        BookingField = new javax.swing.JPanel();
        LabelForFName2 = new javax.swing.JLabel();
        LabelForSName2 = new javax.swing.JLabel();
        LabelForID1 = new javax.swing.JLabel();
        customerID_booking = new javax.swing.JTextField();
        carID_booking = new javax.swing.JTextField();
        Save_booking = new javax.swing.JButton();
        Discard_booking = new javax.swing.JButton();
        add1_booking = new javax.swing.JButton();
        add2_booking = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        problem_booking = new javax.swing.JTextArea();
        AllListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarList_booking = new javax.swing.JList();
        jScrollPaneForStaffList1 = new javax.swing.JScrollPane();
        CustomerList_booking = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookingList_booking = new javax.swing.JList();
        AddCustomer = new javax.swing.JPanel();
        AddField = new javax.swing.JPanel();
        LabelForFName1 = new javax.swing.JLabel();
        LabelForSName1 = new javax.swing.JLabel();
        LabelForConNumber1 = new javax.swing.JLabel();
        LabelForEmailAdd1 = new javax.swing.JLabel();
        LabelForHomeAdd1 = new javax.swing.JLabel();
        Fname_add = new javax.swing.JTextField();
        Sname_add = new javax.swing.JTextField();
        ContactNo_add = new javax.swing.JTextField();
        EmailAdd_add = new javax.swing.JTextField();
        HomeAdd_add = new javax.swing.JTextField();
        addCustomer_add = new javax.swing.JButton();
        discardCustomer_add = new javax.swing.JButton();
        LabelForFName3 = new javax.swing.JLabel();
        LabelForFName4 = new javax.swing.JLabel();
        LabelForFName5 = new javax.swing.JLabel();
        LabelForFName6 = new javax.swing.JLabel();
        Make_add = new javax.swing.JTextField();
        Model_add = new javax.swing.JTextField();
        Regno_add = new javax.swing.JTextField();
        Year_add = new javax.swing.JTextField();
        addCar_add = new javax.swing.JButton();
        discardCar_add = new javax.swing.JButton();
        EditCustomer = new javax.swing.JPanel();
        EditField = new javax.swing.JPanel();
        LabelForFName = new javax.swing.JLabel();
        LabelForSName = new javax.swing.JLabel();
        LabelForConNumber = new javax.swing.JLabel();
        LabelForID = new javax.swing.JLabel();
        LabelForEmailAdd = new javax.swing.JLabel();
        LabelForHomeAdd = new javax.swing.JLabel();
        ID_edit = new javax.swing.JLabel();
        Fname_edit = new javax.swing.JTextField();
        Sname_edit = new javax.swing.JTextField();
        ContactNo_edit = new javax.swing.JTextField();
        EmailAdd_edit = new javax.swing.JTextField();
        HomeAdd_edit = new javax.swing.JTextField();
        Save_edit = new javax.swing.JButton();
        Discard_edit = new javax.swing.JButton();
        Delete_edit = new javax.swing.JButton();
        jScrollPaneForStaffList = new javax.swing.JScrollPane();
        CustomerList_edit = new javax.swing.JList();
        FooterPanel = new javax.swing.JPanel();
        copyrights = new javax.swing.JLabel();
        view_booking = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registered_edit = new javax.swing.JLabel();
        LabelForRegistered = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(938, 580));
        setPreferredSize(new java.awt.Dimension(916, 421));
        setResizable(false);

        //------------------------------------------------------------------Header panel starts here...-----------------------------------------------//
        HeaderPanel.setBackground(new java.awt.Color(255, 255, 204));

        welcomeLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        welcomeLabel.setText("Welcome: ");

        logoutButton.setText("Logout");

        userName.setText("namegoeshere");

        currentDate.setText("dateandtimegoeshere");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                        .addComponent(currentDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                        .addComponent(logoutButton)))
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(currentDate))
                .addContainerGap())
        );

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.PAGE_START);

        //----------------------------------------------------------------Option panel starts here----------------------------------------------//
        OptionPanel.setBackground(new java.awt.Color(255, 255, 204));
        OptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        OptionPanel.setMaximumSize(new java.awt.Dimension(200, 301));
        OptionPanel.setMinimumSize(new java.awt.Dimension(200, 301));
        OptionPanel.setName(""); // NOI18N
        OptionPanel.setPreferredSize(new java.awt.Dimension(200, 301));
        OptionPanel.setLayout(new java.awt.GridLayout(0, 1, 1, 1));

        addCustomer.setText("Add Customer/Car");
        OptionPanel.add(addCustomer);

        editCustomer.setText("Edit Customer");
        OptionPanel.add(editCustomer);

        booking.setText("Booking");
        OptionPanel.add(booking);

        getContentPane().add(OptionPanel, java.awt.BorderLayout.LINE_START);

        //----------------------------------------------------------------Content panel starts here...------------------------------------------------//
        ContentPanel.setLayout(new java.awt.CardLayout());
        
        //----------------------------------------------------Starting panel starts here...------------------------------------------------------//
        StartingPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartingPanel.setPreferredSize(new java.awt.Dimension(602, 247));

        startPanelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startPanelLabel.setText("Click on the buttons on the left hand side to see specific views");

        javax.swing.GroupLayout StartingPanelLayout = new javax.swing.GroupLayout(StartingPanel);
        StartingPanel.setLayout(StartingPanelLayout);
        StartingPanelLayout.setHorizontalGroup(
            StartingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartingPanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(startPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        StartingPanelLayout.setVerticalGroup(
            StartingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartingPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(startPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        ContentPanel.add(StartingPanel, "card0");
        
        //--------------------------------------------------------------Booking panel starts here...-------------------------------------------------//
        BookingPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BookingPanel.setPreferredSize(new java.awt.Dimension(602, 247));

        BookingField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        LabelForFName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName2.setText("Car ID :");

        LabelForSName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForSName2.setText("Problem :");

        LabelForID1.setText("Customer ID :");

        customerID_booking.setEditable(false);
        carID_booking.setEditable(false);

        Save_booking.setText("Save");

        Discard_booking.setText("Discard");

        add1_booking.setText("Add");

        add2_booking.setText("Add");

        problem_booking.setColumns(20);
        problem_booking.setRows(5);
        jScrollPane2.setViewportView(problem_booking);

        javax.swing.GroupLayout BookingFieldLayout = new javax.swing.GroupLayout(BookingField);
        BookingField.setLayout(BookingFieldLayout);
        BookingFieldLayout.setHorizontalGroup(
            BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingFieldLayout.createSequentialGroup()
                .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add1_booking)
                    .addComponent(add2_booking))
                .addGap(18, 18, 18)
                .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingFieldLayout.createSequentialGroup()
                        .addComponent(Discard_booking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Save_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingFieldLayout.createSequentialGroup()
                        .addComponent(LabelForSName2)
                        .addGap(18, 18, 18)
                        .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingFieldLayout.createSequentialGroup()
                                .addComponent(LabelForFName2)
                                .addGap(18, 18, 18)
                                .addComponent(carID_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BookingFieldLayout.createSequentialGroup()
                        .addComponent(LabelForID1)
                        .addGap(18, 18, 18)
                        .addComponent(customerID_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookingFieldLayout.setVerticalGroup(
            BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingFieldLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingFieldLayout.createSequentialGroup()
                        .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelForID1)
                            .addComponent(customerID_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelForFName2)
                            .addComponent(carID_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelForSName2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(BookingFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Save_booking)
                            .addComponent(Discard_booking))
                        .addContainerGap())
                    .addGroup(BookingFieldLayout.createSequentialGroup()
                        .addComponent(add1_booking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add2_booking)
                        .addGap(91, 91, 91))))
        );

        AllListPanel.setLayout(new java.awt.GridLayout(2, 1));

        jScrollPaneForStaffList1.setBorder(javax.swing.BorderFactory.createTitledBorder("All Customer List"));
        jScrollPaneForStaffList1.setPreferredSize(new java.awt.Dimension(50, 130));
        jScrollPaneForStaffList1.setRequestFocusEnabled(false);

        CustomerList_booking.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPaneForStaffList1.setViewportView(CustomerList_booking);

        AllListPanel.add(jScrollPaneForStaffList1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("All Car List"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        CarList_booking.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(CarList_booking);

        AllListPanel.add(jScrollPane1);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Booking List"));

        jScrollPane3.setViewportView(BookingList_booking);

        view_booking.setText("View");

        javax.swing.GroupLayout BookingPanelLayout = new javax.swing.GroupLayout(BookingPanel);
        BookingPanel.setLayout(BookingPanelLayout);
        BookingPanelLayout.setHorizontalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingPanelLayout.createSequentialGroup()
                .addComponent(AllListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        BookingPanelLayout.setVerticalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingPanelLayout.createSequentialGroup()
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view_booking))
                    .addComponent(AllListPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookingField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ContentPanel.add(BookingPanel, "card3");
        
        //-----------------------------------------Adding customer panel starts here------------------------------------------------//
        AddCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddCustomer.setPreferredSize(new java.awt.Dimension(602, 247));

        AddField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

        LabelForEmailAdd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForEmailAdd1.setText("Email Address :");

        LabelForHomeAdd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForHomeAdd1.setText("Home Address :");

        LabelForSName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForSName1.setText("Surname :");

        LabelForConNumber1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForConNumber1.setText("Contact No :");

        discardCustomer_add.setText("Discard");

        addCustomer_add.setText("Save");

        LabelForFName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName1.setText("First Name :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LabelForSName1)
                        .addGap(18, 18, 18)
                        .addComponent(Sname_add, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelForHomeAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HomeAdd_add, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelForEmailAdd1)
                        .addGap(18, 18, 18)
                        .addComponent(EmailAdd_add, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelForConNumber1)
                            .addComponent(LabelForFName1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Fname_add)
                            .addComponent(ContactNo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(addCustomer_add, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(discardCustomer_add)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName1)
                    .addComponent(Fname_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForSName1)
                    .addComponent(Sname_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForConNumber1)
                    .addComponent(ContactNo_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForEmailAdd1)
                    .addComponent(EmailAdd_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForHomeAdd1)
                    .addComponent(HomeAdd_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomer_add)
                    .addComponent(discardCustomer_add))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Car"));

        LabelForFName4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName4.setText("Model :");

        LabelForFName3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName3.setText("Make :");

        LabelForFName6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName6.setText("Year :");

        LabelForFName5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName5.setText("Registration No :");

        addCar_add.setText("Save");

        discardCar_add.setText("Discard");


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LabelForFName6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(LabelForFName4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(LabelForFName3))
                        .addComponent(LabelForFName5, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Make_add)
                    .addComponent(Model_add)
                    .addComponent(Regno_add)
                    .addComponent(Year_add)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(addCar_add, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardCar_add)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName3)
                    .addComponent(Make_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName4)
                    .addComponent(Model_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName5)
                    .addComponent(Regno_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName6)
                    .addComponent(Year_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCar_add)
                    .addComponent(discardCar_add))
                .addContainerGap())
        );

        javax.swing.GroupLayout AddFieldLayout = new javax.swing.GroupLayout(AddField);
        AddField.setLayout(AddFieldLayout);
        AddFieldLayout.setHorizontalGroup(
            AddFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddFieldLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        AddFieldLayout.setVerticalGroup(
            AddFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AddCustomerLayout = new javax.swing.GroupLayout(AddCustomer);
        AddCustomer.setLayout(AddCustomerLayout);
        AddCustomerLayout.setHorizontalGroup(
            AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(AddField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddCustomerLayout.setVerticalGroup(
            AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContentPanel.add(AddCustomer, "card1");

        
        //-----------------------------------------Edit Customer starts here---------------------------------------------//
        EditCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditCustomer.setPreferredSize(new java.awt.Dimension(602, 247));

        EditField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        LabelForFName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForFName.setText("First Name :");

        LabelForSName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForSName.setText("Surname :");

        LabelForConNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForConNumber.setText("Contact No :");

        LabelForID.setText("ID :");

        LabelForEmailAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForEmailAdd.setText("Email Address :");

        LabelForHomeAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForHomeAdd.setText("Home Address :");


        Save_edit.setText("Save");

        Discard_edit.setText("Discard");

        Delete_edit.setText("Delete");

        ID_edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelForRegistered.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelForRegistered.setText("Registered :");

        registered_edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout EditFieldLayout = new javax.swing.GroupLayout(EditField);
        EditField.setLayout(EditFieldLayout);
        EditFieldLayout.setHorizontalGroup(
            EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditFieldLayout.createSequentialGroup()
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditFieldLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditFieldLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelForConNumber)
                                    .addComponent(LabelForSName)
                                    .addComponent(LabelForFName)
                                    .addComponent(LabelForID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EditFieldLayout.createSequentialGroup()
                                        .addComponent(ID_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(LabelForRegistered)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(registered_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                    .addComponent(Fname_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sname_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactNo_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditFieldLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelForEmailAdd)
                                .addGap(18, 18, 18)
                                .addComponent(EmailAdd_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditFieldLayout.createSequentialGroup()
                                .addComponent(LabelForHomeAdd)
                                .addGap(18, 18, 18)
                                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HomeAdd_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EditFieldLayout.createSequentialGroup()
                                        .addComponent(Save_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Discard_edit))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditFieldLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EditFieldLayout.setVerticalGroup(
            EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelForID)
                        .addComponent(LabelForRegistered)
                        .addComponent(registered_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(ID_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForFName)
                    .addComponent(Fname_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForSName)
                    .addComponent(Sname_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForConNumber)
                    .addComponent(ContactNo_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForEmailAdd)
                    .addComponent(EmailAdd_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelForHomeAdd)
                    .addComponent(HomeAdd_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Discard_edit)
                    .addComponent(Save_edit))
                .addGap(18, 18, 18)
                .addComponent(Delete_edit)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jScrollPaneForStaffList.setBorder(javax.swing.BorderFactory.createTitledBorder("All Customer List"));
        jScrollPaneForStaffList.setPreferredSize(new java.awt.Dimension(50, 130));
        jScrollPaneForStaffList.setRequestFocusEnabled(false);

        CustomerList_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPaneForStaffList.setViewportView(CustomerList_edit);

        javax.swing.GroupLayout EditCustomerLayout = new javax.swing.GroupLayout(EditCustomer);
        EditCustomer.setLayout(EditCustomerLayout);
        EditCustomerLayout.setHorizontalGroup(
            EditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCustomerLayout.createSequentialGroup()
                .addComponent(jScrollPaneForStaffList, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        EditCustomerLayout.setVerticalGroup(
            EditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneForStaffList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EditField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContentPanel.add(EditCustomer, "card2");

        getContentPane().add(ContentPanel, java.awt.BorderLayout.CENTER);

        FooterPanel.setBackground(new java.awt.Color(204, 204, 204));

        copyrights.setText("Copyrights 2013, DIT E-Soft Division");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(copyrights)
                .addGap(364, 364, 364))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(copyrights))
        );

        getContentPane().add(FooterPanel, java.awt.BorderLayout.PAGE_END);
        setLocationRelativeTo(null);
        setResizable(false);
        pack();
    }// </editor-fold>                        


    void buttonListener(ActionListener listen)
    {
    	discardCar_add.addActionListener(listen);
    	addCustomer_add.addActionListener(listen);
    	addCar_add.addActionListener(listen);
    	Save_edit.addActionListener(listen);
    	Discard_edit.addActionListener(listen);
    	discardCustomer_add.addActionListener(listen);
    	Save_booking.addActionListener(listen);
    	Discard_booking.addActionListener(listen);
    	add1_booking.addActionListener(listen);
    	add2_booking.addActionListener(listen);
    	addCustomer.addActionListener(listen);
    	editCustomer.addActionListener(listen);
    	booking.addActionListener(listen);
    	logoutButton.addActionListener(listen);
    	Delete_edit.addActionListener(listen);
    	view_booking.addActionListener(listen);
    }
    
    void listSelectionListener(ListSelectionListener listen)
    {
    	CarList_booking.addListSelectionListener(listen);
    	CustomerList_booking.addListSelectionListener(listen);
    	BookingList_booking.addListSelectionListener(listen);
    	CustomerList_edit.addListSelectionListener(listen);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel AddCustomer;
    private javax.swing.JPanel AddField;
    private javax.swing.JPanel AllListPanel;
    private javax.swing.JPanel BookingField;
    protected javax.swing.JList BookingList_booking;
    private javax.swing.JPanel BookingPanel;
    protected javax.swing.JList CarList_booking;
    protected javax.swing.JTextField ContactNo_add;
    protected javax.swing.JTextField ContactNo_edit;
    protected javax.swing.JPanel ContentPanel;
    protected javax.swing.JList CustomerList_booking;
    protected javax.swing.JButton Delete_edit;
    protected javax.swing.JButton Discard_booking;
    protected javax.swing.JButton Discard_edit;
    private javax.swing.JPanel EditCustomer;
    private javax.swing.JPanel EditField;
    protected javax.swing.JTextField EmailAdd_add;
    protected javax.swing.JTextField EmailAdd_edit;
    protected javax.swing.JTextField Fname_add;
    protected javax.swing.JTextField Fname_edit;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel HeaderPanel;
    protected javax.swing.JTextField HomeAdd_add;
    protected javax.swing.JTextField HomeAdd_edit;
    protected javax.swing.JLabel ID_edit;
    private javax.swing.JLabel LabelForConNumber;
    private javax.swing.JLabel LabelForConNumber1;
    private javax.swing.JLabel LabelForEmailAdd;
    private javax.swing.JLabel LabelForEmailAdd1;
    private javax.swing.JLabel LabelForFName;
    private javax.swing.JLabel LabelForFName1;
    private javax.swing.JLabel LabelForFName2;
    private javax.swing.JLabel LabelForFName3;
    private javax.swing.JLabel LabelForFName4;
    private javax.swing.JLabel LabelForFName5;
    private javax.swing.JLabel LabelForFName6;
    private javax.swing.JLabel LabelForHomeAdd;
    private javax.swing.JLabel LabelForHomeAdd1;
    private javax.swing.JLabel LabelForID;
    private javax.swing.JLabel LabelForID1;
    private javax.swing.JLabel LabelForSName;
    private javax.swing.JLabel LabelForSName1;
    private javax.swing.JLabel LabelForSName2;
    protected javax.swing.JTextField Make_add;
    protected javax.swing.JTextField Model_add;
    private javax.swing.JPanel OptionPanel;
    protected javax.swing.JTextField Regno_add;
    protected javax.swing.JButton Save_booking;
    protected javax.swing.JButton Save_edit;
    protected javax.swing.JTextField Sname_add;
    protected javax.swing.JTextField Sname_edit;
    protected javax.swing.JList CustomerList_edit;
    private javax.swing.JPanel StartingPanel;
    protected javax.swing.JTextField Year_add;
    protected javax.swing.JButton add1_booking;
    protected javax.swing.JButton add2_booking;
    protected javax.swing.JButton addCar_add;
    protected javax.swing.JButton addCustomer_add;
    protected javax.swing.JButton addCustomer;
    protected javax.swing.JButton booking;
    protected javax.swing.JTextField carID_booking;
    private javax.swing.JLabel copyrights;
    protected javax.swing.JLabel currentDate;
    protected javax.swing.JTextField customerID_booking;
    protected javax.swing.JButton discardCar_add;
    protected javax.swing.JButton discardCustomer_add;
    protected javax.swing.JButton editCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneForStaffList;
    private javax.swing.JScrollPane jScrollPaneForStaffList1;
    protected javax.swing.JButton logoutButton;
    protected javax.swing.JTextArea problem_booking;
    private javax.swing.JLabel startPanelLabel;
    protected javax.swing.JLabel userName;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration                   
}
